import 'package:flutter/material.dart';
import 'models.dart';

class ProductRepository {
  static final List<Review> _mockReviews = [
    Review(userName: 'Srinivas R.', comment: 'Authentic Andhra taste! Reminds me of home.', rating: 5.0, date: '2 days ago'),
    Review(userName: 'Lakshmi K.', comment: 'High quality spices. Very aromatic.', rating: 5.0, date: '5 days ago'),
    Review(userName: 'Rahul M.', comment: 'Perfect snacks for tea time. Very fresh.', rating: 4.5, date: '1 week ago'),
  ];

  static final List<Product> allProducts = [
    // PICKLES
    Product(
      name: 'Bellam Avakaya', 
      description: 'Sweet jaggery mango pickle', 
      weightPriceMap: {'250g': 140, '500g': 260, '1kg': 500},
      rating: 4.9, image: 'assets/images/bellam_avakaya_sweet_jaggery_mango_pickle.jpg', 
      color: const Color(0xFF18453B), category: 'Pickles', spiceLevel: 2, isBestSeller: true, reviews: _mockReviews,
      pairings: ['Chakinalu', 'Sunnunda Laddu', 'Garam Masala'],
    ),
    Product(
      name: 'Allam Velluli Pickle', 
      description: 'Ginger garlic pickle', 
      weightPriceMap: {'250g': 120, '500g': 220, '1kg': 420},
      rating: 4.9, image: 'assets/images/allam_velluli_pickle_ginger_garlic_pickle.jpg', 
      color: const Color(0xFF18453B), category: 'Pickles', spiceLevel: 3, isBestSeller: true, reviews: _mockReviews,
      pairings: ['Bundhi', 'Gondh Laddu', 'Sambar Masala Powder'],
    ),
    Product(
      name: 'Usiri Pickle', 
      description: 'Amla gooseberry pickle', 
      weightPriceMap: {'250g': 130, '500g': 240, '1kg': 450},
      rating: 4.9, image: 'assets/images/usiri_pickle_amlagooseberry_pickle.jpg', 
      color: const Color(0xFF18453B), category: 'Pickles', spiceLevel: 3, reviews: _mockReviews,
      pairings: ['Rice Papad', 'Millets Laddu', 'Daniya Powder'],
    ),
    Product(
      name: 'Uppava', 
      description: 'Traditional salted pickle', 
      weightPriceMap: {'250g': 100, '500g': 180, '1kg': 340},
      rating: 4.7, image: 'assets/images/uppava_traditional_salted_pickle.jpg', 
      color: const Color(0xFF18453B), category: 'Pickles', spiceLevel: 1, reviews: _mockReviews,
      pairings: ['Allu Chips', 'Sweet Chekki', 'Haldi Powder'],
    ),

    // SNACKS
    Product(
      name: 'Chakinalu', 
      description: 'Traditional spiral snacks', 
      weightPriceMap: {'250g': 100, '500g': 180, '1kg': 350},
      rating: 4.8, image: 'assets/images/chakinalu_traditional_sankranti_spiral_snacks.jpg', 
      color: const Color(0xFF18453B), category: 'Snacks', spiceLevel: 1, reviews: _mockReviews,
      pairings: ['Bellam Avakaya', 'Sunnunda Laddu'],
    ),
    Product(
      name: 'Bundhi', 
      description: 'Crispy gram flour droplets', 
      weightPriceMap: {'250g': 45, '500g': 80, '1kg': 150},
      rating: 4.6, image: 'assets/images/bundhi_crispy_spiced_gram_flour_droplets.jpg',
      color: const Color(0xFF18453B), category: 'Snacks', spiceLevel: 3, reviews: _mockReviews,
      pairings: ['Allam Velluli Pickle', 'Gondh Laddu'],
    ),
    Product(
      name: 'Allu Chips', 
      description: 'Indian potato chips', 
      weightPriceMap: {'250g': 55, '500g': 99, '1kg': 190},
      rating: 4.7, image: 'assets/images/allu_chips_thinly_sliced_indian_potato_chips.jpg', 
      color: const Color(0xFF18453B), category: 'Snacks', spiceLevel: 2, reviews: _mockReviews,
      pairings: ['Uppava', 'Sweet Chekki'],
    ),
    Product(
      name: 'Karam Janthukalu', 
      description: 'Murukku strings snack', 
      weightPriceMap: {'250g': 90, '500g': 160, '1kg': 300},
      rating: 4.8, image: 'assets/images/karam_janthukalu_murukku_strings_snack.jpg', 
      color: const Color(0xFF18453B), category: 'Snacks', spiceLevel: 3, reviews: _mockReviews,
      pairings: ['Usiri Pickle', 'Palli Patti'],
    ),
    Product(
      name: 'Khara Mixture', 
      description: 'Crunchy savory mix', 
      weightPriceMap: {'250g': 70, '500g': 120, '1kg': 230},
      rating: 4.7, image: 'assets/images/khara_mixture_assorted_crunchy_savory_mix.jpg', 
      color: const Color(0xFF18453B), category: 'Snacks', spiceLevel: 4, reviews: _mockReviews,
      pairings: ['Bellam Avakaya', 'Dry Fruits Laddu'],
    ),
    Product(
      name: 'Nuvvula Papad', 
      description: 'Sesame coated papads', 
      weightPriceMap: {'250g': 80, '500g': 140, '1kg': 260},
      rating: 4.7, image: 'assets/images/nuvvula_papad_sesame_coated_crispy_papads.jpg', 
      color: const Color(0xFF18453B), category: 'Snacks', spiceLevel: 1, reviews: _mockReviews,
      pairings: ['Usiri Pickle', 'Millets Laddu'],
    ),
    Product(
      name: 'Onion Whills', 
      description: 'Onion flavored crisp wheels', 
      weightPriceMap: {'200g': 80, '400g': 150, '1kg': 350},
      rating: 4.5, image: 'assets/images/onion_whills_onion_flavored_crisp_wheels.jpg', 
      color: const Color(0xFF18453B), category: 'Snacks', spiceLevel: 2, reviews: _mockReviews,
      pairings: ['Allam Velluli Pickle', 'Kova Gulam Jamun'],
    ),
    Product(
      name: 'Rice Papad', 
      description: 'Crispy rice flour papadums', 
      weightPriceMap: {'250g': 60, '500g': 100, '1kg': 190},
      rating: 4.6, image: 'assets/images/rice_papad_crispy_rice_flour_papadums.jpg', 
      color: const Color(0xFF18453B), category: 'Snacks', spiceLevel: 1, reviews: _mockReviews,
      pairings: ['Usiri Pickle', 'Sunnunda Laddu'],
    ),
    Product(
      name: 'Tomato Chilli Papad', 
      description: 'Tangy and spicy papads', 
      weightPriceMap: {'250g': 70, '500g': 120, '1kg': 230},
      rating: 4.6, image: 'assets/images/tomato_chilli_papad_tangy_and_spicy_papads.jpg', 
      color: const Color(0xFF18453B), category: 'Snacks', spiceLevel: 3, reviews: _mockReviews,
      pairings: ['Bellam Avakaya', 'Thill Patti'],
    ),

    // SPICES
    Product(
      name: 'Allam Velluli Karam Podi', 
      description: 'Ginger garlic spice powder', 
      weightPriceMap: {'250g': 149, '500g': 280, '1kg': 540},
      rating: 4.8, image: 'assets/images/allam_velluli_karam_podi_ginger_garlic_spice_powder.jpg', 
      color: const Color(0xFF18453B), category: 'Spices', spiceLevel: 4, reviews: _mockReviews,
      pairings: ['Bellam Avakaya', 'Rice Papad'],
    ),
    Product(
      name: 'Chicken Masala Powder', 
      description: 'Chicken curry spice blend', 
      weightPriceMap: {'100g': 120, '250g': 280, '500g': 540},
      rating: 4.7, image: 'assets/images/chicken_masala_powder_chicken_curry_spice_blend.jpg', 
      color: const Color(0xFF18453B), category: 'Spices', spiceLevel: 5, reviews: _mockReviews,
      pairings: ['Allam Velluli Pickle', 'Chakinalu'],
    ),
    Product(
      name: 'Daniya Powder', 
      description: 'Coriander powder', 
      weightPriceMap: {'200g': 80, '500g': 190, '1kg': 360},
      rating: 4.5, image: 'assets/images/daniya_powder_freshly_ground_coriander_powder.jpg', 
      color: const Color(0xFF18453B), category: 'Spices', spiceLevel: 1, reviews: _mockReviews,
      pairings: ['Usiri Pickle', 'Bundhi'],
    ),
    Product(
      name: 'Garam Masala', 
      description: 'Traditional warm spice blend', 
      weightPriceMap: {'100g': 150, '250g': 360, '500g': 680},
      rating: 4.8, image: 'assets/images/garam_masala_powder_traditional_warm_spice_blend.jpg', 
      color: const Color(0xFF18453B), category: 'Spices', spiceLevel: 4, reviews: _mockReviews,
      pairings: ['Bellam Avakaya', 'Chakinalu'],
    ),
    Product(
      name: 'Haldi Powder', 
      description: 'Pure turmeric powder', 
      weightPriceMap: {'250g': 90, '500g': 170, '1kg': 320},
      rating: 4.7, image: 'assets/images/haldi_powder_pure_turmeric_powder.jpg', 
      color: const Color(0xFF18453B), category: 'Spices', spiceLevel: 0, reviews: _mockReviews,
      pairings: ['Uppava', 'Rice Papad'],
    ),
    Product(
      name: 'Karvepaku Karam Podi', 
      description: 'Curry leaves powder', 
      weightPriceMap: {'250g': 130, '500g': 240, '1kg': 460},
      rating: 4.9, image: 'assets/images/karvepaku_karam_podi_curry_leaves_powder.jpg', 
      color: const Color(0xFF18453B), category: 'Spices', spiceLevel: 3, reviews: _mockReviews,
      pairings: ['Bellam Avakaya', 'Nuvvula Papad'],
    ),
    Product(
      name: 'Menthi Podi', 
      description: 'Fenugreek powder', 
      weightPriceMap: {'200g': 110, '500g': 260, '1kg': 500},
      rating: 4.6, image: 'assets/images/menthi_podi_fenugreek_powder.jpg', 
      color: const Color(0xFF18453B), category: 'Spices', spiceLevel: 2, reviews: _mockReviews,
      pairings: ['Usiri Pickle', 'Tomato Chilli Papad'],
    ),
    Product(
      name: 'Munagaku Karam Podi', 
      description: 'Moringa leaves spice powder', 
      weightPriceMap: {'250g': 160, '500g': 300, '1kg': 580},
      rating: 4.9, image: 'assets/images/munagaku_karam_podi_moringa_leaves_spice_powder.jpg', 
      color: const Color(0xFF18453B), category: 'Spices', spiceLevel: 3, reviews: _mockReviews,
      pairings: ['Bellam Avakaya', 'Rice Papad'],
    ),
    Product(
      name: 'Mutton Masala Powder', 
      description: 'Mutton recipe spice blend', 
      weightPriceMap: {'100g': 160, '250g': 380, '500g': 720},
      rating: 4.8, image: 'assets/images/mutton_masala_powder_mutton_recipe_spice_blend.jpg', 
      color: const Color(0xFF18453B), category: 'Spices', spiceLevel: 5, reviews: _mockReviews,
      pairings: ['Allam Velluli Pickle', 'Karam Janthukalu'],
    ),
    Product(
      name: 'Putnala Karam Podi', 
      description: 'Roasted gram spice powder', 
      weightPriceMap: {'250g': 110, '500g': 200, '1kg': 380},
      rating: 4.7, image: 'assets/images/putnala_karam_podi_roasted_gram_spice_powder.jpg', 
      color: const Color(0xFF18453B), category: 'Spices', spiceLevel: 3, reviews: _mockReviews,
      pairings: ['Bellam Avakaya', 'Bundhi'],
    ),
    Product(
      name: 'Sambhar Masala Powder', 
      description: 'Sambhar spice blend', 
      weightPriceMap: {'200g': 140, '500g': 330, '1kg': 640},
      rating: 4.8, image: 'assets/images/sambhar_masala_powder_authentic_sambhar_spice_blend.jpg', 
      color: const Color(0xFF18453B), category: 'Spices', spiceLevel: 3, reviews: _mockReviews,
      pairings: ['Usiri Pickle', 'Rice Papad'],
    ),
    Product(
      name: 'Special Idli Karam Podi', 
      description: 'Gun powder spice for idlis', 
      weightPriceMap: {'250g': 150, '500g': 280, '1kg': 540},
      rating: 4.9, image: 'assets/images/special_idli_karam_podi_gun_powder_spice_for_idlis.jpg', 
      color: const Color(0xFF18453B), category: 'Spices', spiceLevel: 4, reviews: _mockReviews,
      pairings: ['Allam Velluli Pickle', 'Chakinalu'],
    ),
    Product(
      name: 'Special Kura Karam Podi', 
      description: 'All-purpose curry powder', 
      weightPriceMap: {'250g': 180, '500g': 340, '1kg': 650},
      rating: 4.8, image: 'assets/images/special_kura_karam_podi_all-purpose_curry_powder.jpg', 
      color: const Color(0xFF18453B), category: 'Spices', spiceLevel: 4, reviews: _mockReviews,
      pairings: ['Bellam Avakaya', 'Rice Papad'],
    ),

    // SWEETS
    Product(
      name: 'Dry Fruits Laddu', 
      description: 'Premium dry fruits laddu', 
      weightPriceMap: {'250g': 240, '500g': 450, '1kg': 880},
      rating: 5.0, image: 'assets/images/dry_fruits_laddu_premium_dry_fruits_laddu.jpg', 
      color: const Color(0xFF18453B), category: 'Sweets', spiceLevel: 0, reviews: _mockReviews,
      pairings: ['Usiri Pickle', 'Bundhi'],
    ),
    Product(
      name: 'Gondh Laddu', 
      description: 'Edible gum laddu', 
      weightPriceMap: {'250g': 200, '500g': 380, '1kg': 740},
      rating: 5.0, image: 'assets/images/gondh_laddu_edible_gum_laddu.jpg', 
      color: const Color(0xFF18453B), category: 'Sweets', isBestSeller: true, spiceLevel: 0, reviews: _mockReviews,
      pairings: ['Allam Velluli Pickle', 'Khara Mixture'],
    ),
    Product(
      name: 'Kova Gulam Jamun', 
      description: 'Gulab jamun sweet', 
      weightPriceMap: {'250g': 150, '500g': 280, '1kg': 540},
      rating: 4.9, image: 'assets/images/kova_gulam_jamun_rich_gulab_jamun_sweet.jpg', 
      color: const Color(0xFF18453B), category: 'Sweets', spiceLevel: 0, reviews: _mockReviews,
      pairings: ['Usiri Pickle', 'Onion Whills'],
    ),
    Product(
      name: 'Millets Laddu', 
      description: 'Multi-millet laddu', 
      weightPriceMap: {'250g': 190, '500g': 350, '1kg': 680},
      rating: 4.9, image: 'assets/images/millets_laddu_wholesome_multi-millet_laddu.jpg', 
      color: const Color(0xFF18453B), category: 'Sweets', spiceLevel: 0, reviews: _mockReviews,
      pairings: ['Bellam Avakaya', 'Tomato Chilli Papad'],
    ),
    Product(
      name: 'Palli Patti', 
      description: 'Peanut and jaggery chikki', 
      weightPriceMap: {'250g': 65, '500g': 120, '1kg': 230},
      rating: 4.8, image: 'assets/images/palli_patti_peanut_and_jaggery_chikki.jpg', 
      color: const Color(0xFF18453B), category: 'Sweets', spiceLevel: 0, reviews: _mockReviews,
      pairings: ['Usiri Pickle', 'Karam Janthukalu'],
    ),
    Product(
      name: 'Sunnunda Laddu', 
      description: 'Roasted urad dal laddu', 
      weightPriceMap: {'250g': 170, '500g': 320, '1kg': 620},
      rating: 4.9, image: 'assets/images/sunnunda_laddu_roasted_urad_dal_laddu.jpg', 
      color: const Color(0xFF18453B), category: 'Sweets', spiceLevel: 0, reviews: _mockReviews,
      pairings: ['Bellam Avakaya', 'Chakinalu'],
    ),
    Product(
      name: 'Sweet Chekki', 
      description: 'Traditional sweet brittle', 
      weightPriceMap: {'250g': 55, '500g': 100, '1kg': 190},
      rating: 4.7, image: 'assets/images/sweet_chekki_traditional_sweet_brittle.jpg', 
      color: const Color(0xFF18453B), category: 'Sweets', spiceLevel: 0, reviews: _mockReviews,
      pairings: ['Uppava', 'Allu Chips'],
    ),
    Product(
      name: 'Thill Patti', 
      description: 'Sesame seed and jaggery sweet', 
      weightPriceMap: {'250g': 70, '500g': 130, '1kg': 250},
      rating: 4.8, image: 'assets/images/thill_patti_sesame_seed_and_jaggery_sweet.jpg', 
      color: const Color(0xFF18453B), category: 'Sweets', spiceLevel: 0, reviews: _mockReviews,
      pairings: ['Usiri Pickle', 'Tomato Chilli Papad'],
    ),
  ];
}
